rtabmap:
  frame_id: camera_link
  subscribe_rgb: true
  subscribe_depth: true
  rgb_topic: /camera/color/image_raw
  depth_topic: /camera/depth/image_raw
  camera_info_topic: /camera/color/camera_info
